"""
evaluate.py
Computes hit rate and MRR for rag.retrieve() against the ground-truth
questions generated by generate_ground_truth.py, following the standard
llm-zoomcamp retrieval evaluation pattern.

Usage:
    python evaluate.py
    python evaluate.py --ground-truth data/ground-truth-retrieval.csv --top-k 5
"""

import argparse

import pandas as pd
from tqdm.auto import tqdm

import rag


def hit_rate(relevance_total):
    cnt = 0
    for line in relevance_total:
        if True in line:
            cnt += 1
    return cnt / len(relevance_total)


def mrr(relevance_total):
    total_score = 0.0
    for line in relevance_total:
        for rank in range(len(line)):
            if line[rank]:
                total_score += 1 / (rank + 1)
                break
    return total_score / len(relevance_total)


def make_search_function(top_k: int = rag.TOP_K, table_fqn: str | None = None):
    """rag.retrieve() returns (id, question, answer, distance) tuples - this
    wraps it into the {"id": ..., ...} shape evaluate() expects, and lets
    you fix top_k/table_fqn for the run without changing rag.py's defaults."""

    def search_function(q: dict):
        results = rag.retrieve(q["question"], top_k=top_k, table_fqn=table_fqn)
        return [
            {"id": doc_id, "question": question, "answer": answer, "distance": distance}
            for doc_id, question, answer, distance in results
        ]

    return search_function


def evaluate(ground_truth, search_function):
    relevance_total = []
    for q in tqdm(ground_truth):
        doc_id = q["id"]
        results = search_function(q)
        relevance = [d["id"] == doc_id for d in results]
        relevance_total.append(relevance)
    return {
        "hit_rate": hit_rate(relevance_total),
        "mrr": mrr(relevance_total),
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--ground-truth", default="/home/lauosgom/anomaly/llamatel-crisis-lifeline-chatbot/data/ground-truth-retrieval.csv")
    parser.add_argument("--top-k", type=int, default=rag.TOP_K)
    parser.add_argument(
        "--table-id",
        default=None,
        help="Override which BigQuery table to evaluate against (same project/dataset as .env). "
        "Defaults to whatever rag.py is already configured to use.",
    )
    args = parser.parse_args()

    df = pd.read_csv(args.ground_truth)
    ground_truth = df.to_dict(orient="records")

    table_fqn = None
    if args.table_id:
        table_fqn = f"{rag.PROJECT_ID}.{rag.DATASET_ID}.{args.table_id}"

    search_function = make_search_function(top_k=args.top_k, table_fqn=table_fqn)
    metrics = evaluate(ground_truth, search_function)

    print(f"\nEvaluated {len(ground_truth)} questions (top_k={args.top_k}, table={table_fqn or rag.TABLE_FQN}):")
    print(f"  hit_rate: {metrics['hit_rate']:.3f}")
    print(f"  mrr:      {metrics['mrr']:.3f}")


if __name__ == "__main__":
    main()